version: '3'
services:
    shopxophp:
        build: ./shopxophp
        restart: always
        ports:
            - "10000:80"
    
    shopxomysqldb:
        image: mysql:5.7    
        container_name: shopxomysqldb
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_DATABASE=db
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pass
